wutsi:
  client-id: wutsi-notification
  platform:
    security:
      api-key: ${API_KEY}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
    url-shortener:
      bitly:
        access-token: ${BITLY_ACCESS_TOKEN}

