
wutsi:
  client-id: wutsi-notification
  platform:
    security:
      type: jwt
      api-key: ${API_KEY}
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

