name: scheduled_run

on:
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"   # Every 3hr

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          curl -sSf https://wutsi-tracking-notification-test.herokuapp.com/actuator/health >> /dev/null
